sudo: required
cache:
  - apt

language: generic
matrix:
  include:
  - name: "Xenial kinetic"
    dist: xenial
    env: ROS_DISTRO=kinetic

env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    - CI_SOURCE_PATH=$(pwd)
    - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    - ROS_PARALLEL_JOBS='-j8 -l6'
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

################################################################################

before_install:

   #install gtest
  - sudo apt-get update                     >/dev/null # suppress output
  - sudo apt-get install cmake              >/dev/null # suppress output
  - sudo apt install libgtest-dev           >/dev/null # suppress output
  - cd /usr/src/gtest/                      >/dev/null # suppress output
  - sudo mkdir build && cd build            >/dev/null # suppress output
  - sudo cmake .. -DBUILD_SHARED_LIBS=ON    >/dev/null # suppress output
  - sudo make                               >/dev/null # suppress output
  - sudo cp *.so /usr/lib                   >/dev/null # suppress output
  - cd ~/                                   >/dev/null # suppress output

   #install ros kinetic
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'  >/dev/null # suppress output
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -   >/dev/null # suppress output
  - sudo apt-get update   >/dev/null # suppress output
  - sudo apt-get install python-catkin-tools  >/dev/null # suppress output
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"  >/dev/null # suppress output
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116  >/dev/null # suppress output
  - sudo apt-get update   >/dev/null # suppress output
  - sudo apt-get install -y python-catkin-pkg python-rosdep ros-$ROS_DISTRO-ros-base  >/dev/null # suppress output
  - source /opt/ros/$ROS_DISTRO/setup.bash  >/dev/null # suppress output
  # Prepare rosdep to install dependencies.
  - sudo rosdep init  >/dev/null # suppress output
  - rosdep update  >/dev/null # suppress output


  - sudo apt-get update                 
  - sudo apt-get install liblapack-dev
  - sudo apt-get install libeigen3-dev
  - sudo apt-get install cmake
  - sudo apt-get install ros-kinetic-tf2
  - sudo apt-get install ros-kinetic-tf2-ros
  - sudo apt-get install ros-kinetic-dynamic-reconfigure


# Create a catkin workspace with the package under integration.
install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws
  - catkin init
  # Add the package under integration to the workspace using a symlink.
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .

  #install dependencies
  - cd ~/catkin_ws/src/
  - git clone https://github.com/ANYbotics/kindr.git
  - git clone https://github.com/ethz-adrl/control-toolbox.git

script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - cd ~/catkin_ws
  - catkin clean --all
  - catkin config --blacklist ct_doc
  - catkin build ct_models -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-w"
  - catkin build ct_ros_nodes -v -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-w"

